name: "Nodejs e2e Tests"
on:
  push:
    branches: [ e2e_tests ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    name: E2E-Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci 
      - name: Run tests 
        run: npm test
        env:
          PGPASSWORD: noodle

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: ./junit.xml    # Path to test results
          reporter: jest-junit

